#pragma once
#include <Windows.h>
#include <wrl/client.h>
#include <initguid.h>
#include <directx/d3d12.h>
#include <directx/d3dx12.h>
#include <D3Dcompiler.h>
#include <dxgi1_6.h>
#include <dxgidebug.h>
#define GLFW_EXPOSE_NATIVE_WIN32
#include <GLFW/glfw3native.h>