#pragma once
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include <glm/glm.hpp>
#include <spdlog/spdlog.h>
#include <string>
#include <fstream>
#include <iostream>
#include <sstream>
#include <cstdint>
#include <stddef.h>
#include <unordered_map>
#include <memory>
#include <vector>
#include <list>
#include <typeinfo>
#include <stdexcept>