name: build
on: push
jobs:
  build:
    runs-on: ${{ matrix.os-name }}-latest
    strategy:
      matrix:
        os-name: [ windows, ubuntu, macos ]
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: sync ubuntu dependencies
        if: ${{ matrix.os-name == 'ubuntu' }}
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-common-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev cmake
      - name: configure
        shell: bash
        run: |
          cmake . -B build -DCMAKE_BUILD_TYPE=Release
      - name: build!
        shell: bash
        run: |
          cmake --build build --config Release -j 8